<?php

class AdwordsMapper {

    private $sources = array(
        'tnsw' => 'Transport NSW',
        'yt' => 'YouTube Ads',
        'ytv' => 'YouTube Ads',
        'ytvrm' => 'YouTube Vid Rem',
        'ytb' => 'YouTube Banners',
        'ld' => 'LinkedIn Ads',
        'ldg' => 'LinkedIn Generic',
        'tw' => 'Twitter',
        'tpr' => 'Trades Pre-Roll',
        'ldim' => 'LinkedIn InMail',
        'cos' => 'CareerOne CS',
        'codhh' => 'CareerOne DHH',
        'conet' => 'CareerOne Networker',
        'coco' => 'CareerOne Courses',
        'cew' => 'CareerOne EDM Video',
        'cob' => 'CareerOne Banners',
        'csol' => 'CareerOne Solus',
        'coss' => 'CareerOne Saved Search',
        'rm' => 'ReMarketing',
        'tl' => 'Trade License Campaign',
        'seek' => 'Google Banners',
        'jr' => 'JobsRapido',
        'mraw' => 'Google AdWords',
        'mrawr' => 'Google AdWords - RPL',
        'mrawg' => 'Google AdWords - General',
        'mrawt' => 'Google AdWords - Trades',
        'mrawts' => 'Google AdWords - Trade Services',
        'mrawq' => 'Google AdWords - Qualifications',
        'mrawtl' => 'Google AdWords - Trades Licence',
        'mrawc' => 'Google AdWords - Competitors',
        'gbt' => 'Google Banners - Trades',
        'gbnt' => 'Google Banners - Non-Trades',
        'gael' => 'Google Adwords - Electro',
        'gatc' => 'Google Adwords - Training Courses',
        'gagen' => 'Google Adwords - Training Courses',
        'gfbtrm' => 'Google - Facebook Trades Remarket',
        'gfbntrm' => 'Google - Facebook NonTrades Remarket',
        'gahosp' => 'Google Adwords - Hospitality',
        'gaauto' => 'Google Adwords - Automotive',
        'gahort' => 'Google Adwords - Horticulture',
        'gabeaut' => 'Google Adwords - Beauty',
        'gatrans' => 'Google Adwords - Transport Logistics',
        'gatrain' => 'Google Adwords - Training Education',
        'gasus' => 'Google Adwords - Sustainability',
        'gasport' => 'Google Adwords - Sport Fitness',
        'garetail' => 'Google Adwords - Retail',
        'gares' => 'Google Adwords - Mining',
        'gaprop' => 'Google Adwords - Property Services',
        'gamet' => 'Google Adwords - Metal Engineering',
        'gamanu' => 'Google Adwords - Manufacturing',
        'gaheal' => 'Google Adwords - Health',
        'gahair' => 'Google Adwords - Hairdressing',
        'gafurn' => 'Google Adwords - Furnishing',
        'gafound' => 'Google Adwords - Foundation Skills',
        'gafood' => 'Google Adwords - Food Processing',
        'gafin' => 'Google Adwords - Financial Services',
        'gacons' => 'Google Adwords - Construction Plumbing',
        'gacomm' => 'Google Adwords - Community Services',
        'gabus' => 'Google Adwords - Business Services',
        'gaold' => 'Google Adwords - Old LP',
        'gacqf' => 'Google Adwords - Competitors QF',
        'gdnco' => 'Google Display - Construction',
        'gacar' => 'Google Adwords - Carpentry',
        'gaconsc' => 'Twitter - Construction Plumbing - C',
        'gaskrec' => 'Google Adwords - Australia Skills Recognition',
        'gagqaus' => 'Google Adwords - GQ Australia',
        'gamin' => 'Google Adwords - Mining',
        'gaqds' => 'Google Adwords - Qual Diploma Skills',
        'gaqme' => 'Google Adwords - Qualify Me',
        'gabcg' => 'Google Adwords - Building Construction - G',
        'gaengs' => 'Google Adwords - Engineering - S',
        'gacertiii' => 'Google Adwords - Cert III',
        'gacertiv' => 'Google Adwords - Cert IV',
        'gaskillsa' => 'Google Adwords - Skills Assessment',
        'gabuild' => 'Google Adwords - Building',
        'gaavia' => 'Google Adwords - AVI',
        'gabusma' => 'Google Adwords - Business Management',
        'gacommse' => 'Google Adwords - Community Service',
        'gaglag' => 'Google Adwords - Glass Glazing',
        'gainft' => 'Google Adwords - Information Technology',
        'gapubsa' => 'Google Adwords - Public Safety',
        'gapubsec' => 'Google Adwords - Public Sector',
        'gatexclo' => 'Google Adwords - Textiles Clothing',
        'gagencer' => 'Google Adwords - Generic Cert',
        'gamba' => 'Google Adwords - MBA',
        'ebvrm1' => 'Ebook Video Remarketing 1',
        'gmail' => 'Google Gmail',
        'gagenemp' => 'Google - EMP',
        'gajrdec' => 'Google - JR',
        'gacarau' => 'Google - CARAU',
        'gajrdecmel' => 'Google - JR -MEL',
        'atc' => 'ATC EDM',		
        // 2016 AdWords
        // ## RPL SPECIFIC ##
        '16garple' => 'Google S - RPL - E',
        '16garplp' => 'Google S - RPL - P',
        '16garplb' => 'Google S - RPL - B',
        // ## BUSINESS SERVICES ##
        '16sqsbse' => 'Google S - QS BSTP - E',
        '16sqsbsb' => 'Google S - QS BSTP - B',
        '16sqsbsp' => 'Google S - QS BSTP - P',
        // ## BUILDING & CONSTRUCTION ##
        '16sqsbce' => 'Google S - QS BCTP - E',
        '16sqsbcp' => 'Google S - QS BCTP - P',
        '16sqsbcb' => 'Google S - QS BCTP - B',
        // ## BUILDING & CONSTRUCTION ##
        '16sjrbce' => 'Google S - JR BCTP - E',
        '16sjrbcp' => 'Google S - JR BCTP - P',
        '16sjrbcb' => 'Google S - JR BCTP - B',
        // ## RESOURCE & INFRASTRUCTURE ##
        '16sqsrese' => 'Google S - QS RESTP - E',
        '16sqsresp' => 'Google S - QS RESTP - P',
        '16sqsresb' => 'Google S - QS RESTP - B',
        // ## COMMUNITY SERVICES ##
        '16sqscome' => 'Google S - QS COMTP - E',
        '16sqscomb' => 'Google S - QS COMTP - B',
        '16sqscomp' => 'Google S - QS COMTP - P',
        // ## ENGINEERING ##
        '16sqsenge' => 'Google S - QS ENGTP - E',
        '16sqsengb' => 'Google S - QS ENGTP - B',
        '16sqsengp' => 'Google S - QS ENGTP - P',
        // ## HOSPITALITY ##
        '16sqshose' => 'Google S - QS HOSTP - E',
        '16sqshosb' => 'Google S - QS HOSTP - B',
        '16sqshosp' => 'Google S - QS HOSTP - P',
        // ## AUTOMOTIVE ##
        '16sqsaute' => 'Google S - QS AUTTP - E',
        '16sqsautb' => 'Google S - QS AUTTP - B',
        '16sqsautp' => 'Google S - QS AUTTP - P',
        // ## PUBLIC SERVICE ##
        '16sqspube' => 'Google S - QS PUBTP - E',
        '16sqspubb' => 'Google S - QS PUBTP - B',
        '16sqspubp' => 'Google S - QS PUBTP - P',
        // ## FINANCE ##
        '16sqsfine' => 'Google S - QS FINTP - E',
        '16sqsfinb' => 'Google S - QS FINTP - B',
        '16sqsfinp' => 'Google S - QS FINTP - P',
        // ## ELECTRO ##
        '16sqselee' => 'Google S - QS ELETP - E',
        '16sqseleb' => 'Google S - QS ELETP - B',
        '16sqselep' => 'Google S - QS ELETP - P',
        // ## MBA DISPLAY ##
        '16drmba' => 'Google D - R - MBA',
        '16dfmba' => 'Google D - F - MBA',
        '16drmmba' => 'Google D - RM - MBA',
        '16gspmba' => 'Google GSP - MBA',
        // ## SPORT & FITNESS ##
        '16sqsspoe' => 'Google S - QS SPOTP - E',
        '16sqsspob' => 'Google S - QS SPOTP - B',
        '16sqsspop' => 'Google S - QS SPOTP - P',
        // ## TRANSPORT & LOGISTICS ##
        '16sqstrae' => 'Google S - QS TRATP - E',
        '16sqstrab' => 'Google S - QS TRATP - B',
        '16sqstrap' => 'Google S - QS TRATP - P',
        // ## AGRICULTURE & HORTICULTURE ##
        '16sqsagre' => 'Google S - QS AGRTP - E',
        '16sqsagrb' => 'Google S - QS AGRTP - B',
        '16sqsagrp' => 'Google S - QS AGRTP - P',
        // ## HEALTH ##
        '16sqsheae' => 'Google S - QS HEATP - E',
        '16sqsheab' => 'Google S - QS HEATP - B',
        '16sqsheap' => 'Google S - QS HEATP - P',
        '16ssl' => 'Google S - Sitelink',
        // Bing
        'be' => 'Bing - Electro',
        'bco' => 'Bing - Competitors',
        'bge' => 'Bing - General',
        'btl' => 'Bing - Trade Licence',
        'bqual' => 'Bing - Qualifications',
        'brpl' => 'Bing - RPL',
        'btra' => 'Bing - Trades',
        'bhosp' => 'Bing - Hospitality',
        'btrli' => 'Bing - Trades Licence',
        'bires' => 'Bing - Resource Infrastructure',
        'bitraic' => 'Bing - Training Courses',
        'biauto' => 'Bing - Automotive',
        'bibeaut' => 'Bing - Beauty',
        'bibus' => 'Bing - Business',
        'bifin' => 'Bing - Financial',
        'bifood' => 'Bing - Food',
        'bifound' => 'Bing - Foundation Skills',
        'bihair' => 'Bing - Hairdressing',
        'biheal' => 'Bing - Health',
        'bimet' => 'Bing - Metal Engineering',
        'biprop' => 'Bing - Property Services',
        'bispor' => 'Bing - Sports Fitness',
        'bisust' => 'Bing - Sustainability',
        'bicomm' => 'Bing - Community Services',
        'biconst' => 'Bing - Construction Plumbing',
        'bihort' => 'Bing - Agriculture Horticulture',
        'bihosp' => 'Bing - Hospitality',
        'bifurn' => 'Bing - Furnishing',
        'bimanu' => 'Bing - Manufacturing',
        'bireta' => 'Bing - Retail',
        'bitrain' => 'Bing - Training Education',
        'bitrans' => 'Bing - Transport Logistics',
        'biqds' => 'Bing - Qual Diploma Skills',
        'bigqaus' => 'Bing - GQ Australia',
        'biauskr' => 'Bing - Australia Skills Recognition',
        'biqumau' => 'Bing - Qualify Me',
        'bijrdec' => 'Bing - JR',
        // Other
        'hc' => 'HotCourses',
        'b' => 'Bing Ads',
        'mx' => 'MX News Sydney',
        'ar' => 'AdRoll',
        'mmm' => '3MMM Banners',
        'yh' => 'Yahoo7',
        'yhau' => 'Yahoo7 Audience',
        'ff' => 'Fairfax Banners',
        'trv' => 'Travel Emails',
        'rmd' => 'RMD EDM',
        'rmds' => 'RMD Site',
        'om' => 'Oz Mining',
        'ahrip' => 'AHRI Print',
        'tb' => 'The Brag',
        'lbtr' => 'Letterbox AAM - Trades',
        'lbsyd' => 'Letterbox Sydney - Trades',
        'aaoa' => 'AAoA',
        'adbo' => 'Adblade',
        's8' => 'Survey Email',
        'cafaq' => 'Career FAQ',
        'apdnt' => 'APD NT',
        'insta' => 'Instagram',
        'qt' => 'QT',
        'nlpvv' => 'NLP Video View',
        'ifsem' => 'Lead Nurturing',
        'yhbus' => 'Yahoo Business',
        'revpro' => 'Rev Content Professional',
        'stadpro' => 'StAd Professional',
        'exomba' => 'EXO MBA',
        'getinmba' => 'GETIN MBA',
        'ssmba' => 'SS MBA',
        'pomamba' => 'POMA MBA',
        'westin' => 'Westin Hotel',
        'newcrest' => 'Newcrest Mining',
        'webmba' => 'Website - MBA',
        'webmban' => 'Website - MBA New',
        'yhmba' => 'Yahoo MBA',
        'vhmlg' => 'VHM Lead Gen',		
        // Facebook
        'fbm' => 'Facebook Trades CPM',
        'fb' => 'Facebook Trades',
        'fbg' => 'Facebook Non-Trades',
        'fbtn' => 'Facebook Trades New',
        'fbgm' => 'Facebook Micro Target',
        'fbtmt' => 'Facebook Trades Micro Target',
        'fbc' => 'Facebook Target C',
        'fbbt' => 'Facebook Business Target',
        'fbct' => 'Facebook Cookery Target',
        'fbv' => 'Facebook Video',
        'fbctt' => 'Facebook Conversion Test',
        'fbtd' => 'Facebook Trades Demo',
        'fbd' => 'Facebook Day',
        'fbb' => 'Facebook Broad',
        'fbsr' => 'Facebook Sales Retail',
        'fbs' => 'Facebook Seek',
        'fboc' => 'Facebook Open Colleges',
        'fbt' => 'Facebook Tafe',
        'fbtcpm' => 'Facebook Tafe CPM',
        'fboctt' => 'Facebook Oct Trades',
        'fboct' => 'Facebook Oct',
        'fbmin' => 'Facebook Mining',
        'fbtocpm' => 'Facebook Trades Broad oCPM',
        'fbcmt' => 'Facebook Community',
        'lv' => 'Facebook Lookalike Visitors',
        'll' => 'Facebook Lookalike Leads',
        'fb17' => 'Facebook 17',
        'fbnynt' => 'Facebook New Years NonTrades',
        'fbnyt' => 'Facebook New Years Trades',
        'fbr' => 'Facebook R Test',
        'fbmm' => 'Facebook M',
        'fbtll' => 'Facebook Trades Lookalike',
        'fbnl' => 'Facebook 14 NL',
        'fbq' => 'Facebook Queensland',
        'fbe' => 'Facebook Electro',
        'fbhosp' => 'Facebook Hospitality',
        'fbhort' => 'Facebook Horticulture',
        'fbauto' => 'Facebook Automotive',
        'fbbea' => 'Facebook Beauty',
        'fbbus' => 'Facebook Business',
        'fbcomm' => 'Facebook Community Service',
        'fbconst' => 'Facebook Construction Plumbing',
        'fbconst' => 'Facebook Construction Plumbing',
        'fbfin' => 'Facebook Financial',
        'fbfoo' => 'Facebook Food Processing',
        'fbfound' => 'Facebook Foundation Skills',
        'fbfurn' => 'Facebook Furninshing',
        'fbhair' => 'Facebook Hairdressing',
        'fbhea' => 'Facebook Health',
        'fbmanu' => 'Facebook Manufacturing',
        'fbmet' => 'Facebook Metal Engineering',
        'fbprop' => 'Facebook Property Services',
        'fbres' => 'Facebook Resource Infrastructure',
        'fbret' => 'Facebook Retail Services',
        'fbsport' => 'Facebook Sports Fitness',
        'fbsus' => 'Facebook Sustainability',
        'fbtrain' => 'Facebook Training Education',
        'fbtrans' => 'Facebook Transport Logistics',
        'fbcarp' => 'Facebook Carpentry',
        'fbplum' => 'Facebook Plumbing',
        'fbbucon' => 'Facebook Building Construction',
        'fbmin' => 'Facebook Mining',
        'fbvrm' => 'Facebook Vid Rem',
        'fbenot' => 'Facebook Engineering 2 - Oth',
        'fbenen' => 'Facebook Engineering 2 - Eng',
        'fbenau' => 'Facebook Engineering 2 - Auto',
        'fbenho' => 'Facebook Engineering 2 - Hort',
        'fbbrbu' => 'Facebook N - BC',
        'fbbrau' => 'Facebook N - Auto',
        'fbbren' => 'Facebook N - Eng',
        'fbbrcar' => 'Facebook N - Carpentry',
        'fbbrplu' => 'Facebook N - Plumbing',
        'fbbroth' => 'Facebook N - Other',
        'fbpbo' => 'Facebook PreBook - Other',
        'fbpaut' => 'Facebook PreBook - Auto',
        'fbpbbc' => 'Facebook PreBook - BC',
        'fbpbeng' => 'Facebook PreBook - Eng',
        'fbpbcar' => 'Facebook PreBook - Carpentry',
        'fbpbplu' => 'Facebook PreBook - Plumbing',
        'fbwsll' => 'Facebook - Website Lookalike',
        'ntll' => 'Facebook Non Trades Lookalike',
        'fbbrick' => 'Facebook Bricklaying',
        'fbtrades' => 'Facebook Trades',
        'fbtravou' => 'Facebook 250 Trades Discount',
        'fbtravou10' => 'Facebook 10 Percent Trades Discount',
        'fbef' => 'Facebook Enquire Form',
        'fbbn' => 'Facebook BN',
        'fbsps' => 'Facebook SPS',
        'fbotl' => 'Facebook OTL',
        'fblgcon' => 'Facebook LGCON',
        'fbexp' => 'Facebook EXP',
        'fblife' => 'Facebook Life',
        'fbcuoc' => 'Facebook CUO',
        'fbmt' => 'Facebook MT',
        'ntcll' => 'Facebook NT Cust Lookalike',
        'fbtue' => 'Facebook TUE',
        'fbvpro' => 'Facebook vPro',
        'fbfsr' => 'Facebook FSR TW',
        'fbp1' => 'Facebook Phase 1 M',
        'fbp2' => 'Facebook Phase 2 M',
        'fbpd1' => 'Facebook Phase 1 D',
        'fbpd2' => 'Facebook Phase 2 D',
        'fbjsd' => 'Facebook JS - D',
        'fbjsm' => 'Facebook JS - M',
        'fbtlad' => 'Facebook TLA - D',
        'fbtlam' => 'Facebook TLA - M',
        'fb90cc' => 'Facebook 90 - CC',
        'fbaudco' => 'Facebook Aud Co',
        'fbdecpro' => 'Facebook RM December Promo',
        'fbdecpro1' => 'Facebook December Promo',
        'fbmanage' => 'Facebook Management',
        'fbmba' => 'MBA - Facebook',
        'fbmbarm' => 'Facebook - MBA - RM',
        'fb15febt' => 'Facebook - 15 Trades',
        'fbflife' => 'Facebook - F - Life',
        'fbsrrm' => 'Facebook - SR - RM',
        'fbaged' => 'Facebook - Aged',
        'fb16trt' => 'Facebook - 2016 Trades Test',
        'fb16agri' => 'Facebook - 2016 Agriculture',
        // Facebook																																																																																																																																				
        'e0' => 'eBook 0',
        'e1' => 'eBook 1'
    );

    public function getParam($source) {
        if (isset($this->sources[$source])) {
            return $this->sources[$source];
        }
    }

}

// end of class
?>